sudo: required
language: generic

services:
          - docker

before_install:
          - docker build -t gkalan/react-test -f ./client/Dockerfile.dev ./client

script:
          - docker run -e CI=true gkalan/react-test npm test

after_success:
          - docker build -t gkalan/multi-client ./client
          - docker build -t gkalan/multi-nginx ./nginx
          - docker build -t gkalan/multi-server ./server
          - docker build -t gkalan/multi-worker ./worker
          # Log in to the docker CLI
          - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
          # Take those images and push them to docker hub
          - docker push gkalan/multi-client
          - docker push gkalan/multi-nginx
          - docker push gkalan/multi-server
          - docker push gkalan/multi-worker
